"""Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
 four million, find the sum of the even-valued terms."""

fib_list = [1, 2]


def generating_fibonachi_numbers():
    n = 0
    while True:
        new_number = fib_list[n] + fib_list[n + 1]
        # print(new_number)
        fib_list.append(new_number)
        n = n + 1
        if new_number > 4000000:
            del fib_list[-1]
            # print(fib_list)
            break


def sum_even_fibon_numbers():
    new_list = []
    for num in fib_list:
        if num % 2 == 0:
            new_list.append(num)
    print(f"Result is {sum(new_list)}")


generating_fibonachi_numbers()
sum_even_fibon_numbers()

